introduction_text = '''Student hara-kiri is a project created by 3 students from DNU. It features an ensemble with an accuracy rate of 96%. For more information, visit us on our github page https://github.com/MichailoZaichenko/student_hara_kiri'''

model_2_introduction_text = '''This model is optimized for speed, while sacrificing a little accuracy. It features a SVM with an accuracy rate of 95%. For more information, visit us on our github page https://github.com/MichailoZaichenko/student_hara_kiri'''

threshold_info = "Adjusting the threshold will change the sensitivity of the model. A threshold of example 0.8 means that the model will label the text as AI-written only if it is 80% confident. By decreasing the threshold, the model will be more sensitive to AI-written texts. On the other hand, increasing the threshold will reduce cases where human-written text is falsely labelled as AI-written as the model is less sensitive."

paraphrase_checker_info = "Text generated from ChatGPT can be modified by users, making detection more ambiguous. Our paraphrase detection model was trained on ChatGPT generated text, that was augmented by T5 Transformers. It will return the probability of the response being a paraphrased ChatGPT response. There are some limitations as we used a T5 transformer to automate the paraphrasing so it may not closely resemble the paraphrasing tendencies of a human. Thus, this model is not perfect and should be used with caution."

paraphrase_threshold_info = "Adjusting the threshold will change the sensitivity of the model. A threshold of example 0.8 means that the model will label the text as Paraphrased-AI only if it is 80% confident. By decreasing the threshold, the model will be more sensitive to Paraphrased-AI texts. On the other hand, increasing the threshold will reduce cases where human-written text is falsely labelled as Paraphrased-AI as the model is less sensitive."

explanation_info = "This feature will generate an explanation for why the model thinks the text is written by AI. The explanation is generated using the LIME library and shows the top features that contributed to the model's prediction. The explanation will also show the probability of the text being written by AI for each model. Currently, only SVM is supported due to the high computational cost of generating explanations for BERT and CNN."

version_info = "The models on the ensemble were trained on the whole text so the Short-Text version will likely be more accurate. However, for long text inputs, the prediction will only be based on the first part of the text that is within the token limit. E.g. if the text has multiple paragraphs and  the last paragraph is AI-written, the model may not detect this text as AI because it would only have done the prediction based on the first few paragraphs. If you are intending to do detection on a long text, you can opt for the Essay version because we will split your text into chunks, predict on each chunk and aggregate the predictions."
